//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_Virtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> edad { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string fechaNacimiento { get; set; }
        public string carrera { get; set; }
        public string codigo { get; set; }
    
        public virtual Carreras Carreras { get; set; }
    }
}
