//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_Virtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secciones
    {
        public int id { get; set; }
        public string clase { get; set; }
        public string hora { get; set; }
        public string aula { get; set; }
        public string cupos { get; set; }
        public string maestro { get; set; }
        public string codigo { get; set; }
        public Nullable<int> idMaestro { get; set; }
    
        public virtual clases clases { get; set; }
        public virtual Maestros Maestros { get; set; }
    }
}
